/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MainChart: typeof import('./components/MainChart.vue')['default']
    MiniChart: typeof import('./components/MiniChart.vue')['default']
    News: typeof import('./components/News.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screener: typeof import('./components/Screener.vue')['default']
    TickerTape: typeof import('./components/TickerTape.vue')['default']
  }
}
